name: Release

on: workflow_dispatch

jobs:
    run_and_release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                  python-version: 3.9
            - name: Install Poetry
              run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
            - name: Add Poetry to path
              run: echo "${HOME}/.poetry/bin" >> $GITHUB_PATH
            - name: Install Requirements
              run: poetry install
            - name: Run Script
              run: chmod +x start.sh && ./start.sh
            - name: Check errors
              run: |
                  if  [[ -f "error.png" ]]; then
                      curl --upload-file "error.png" "https://transfer.sh/error.png"
                  fi
            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: "v0.1.3"
                  name: Release
                  draft: false
                  files: ./release/*
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
